# Generated by Django 5.0.3 on 2024-03-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=30)),
            ],
        ),
    ]
