# Generated by Django 5.0.3 on 2024-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
