version: '3.8'

services:
  web:
    build: .
    container_name: pyApp_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=webApp.settings
